name: UI Tests

on:
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud SDK
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: firebase-test-runner@YOUR_PROJECT_ID.iam.gserviceaccount.com
          project_id: YOUR_PROJECT_ID
          version: 300.0.0

      - name: Run UI tests on virtual devices
        run: |
          gcloud firebase test android run \
            --type instrumentation \
            --app ./app/build/outputs/apk/debug/app-debug.apk \
            --test ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --device model=NexusLowRes,version=28 \
            --device model=NexusLowRes,version=29 \
            --environment-variables coverage=true,coverageFile="lcov.info" \
            --timeout 10m

      - name: Run UI tests on physical devices
        run: |
          gcloud firebase test android run \
            --type instrumentation \
            --app ./app/build/outputs/apk/debug/app-debug.apk \
            --test ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk \
            --device model=YOUR_PHYSICAL_DEVICE_MODEL \
            --environment-variables coverage=true,coverageFile="lcov.info" \
            --timeout 10m
